### ISSUE TITLE
Error or not : Loss about Relation Classification

### ISSUE THREAD

**Issue by HuizhaoWang** [markus-eberts/spert#46] opened 2021-04-28 04:41 UTC
Hi,
Thanks for sharing such a wonderful work. I am studying the code and found a problem about the relation calssification(may not).
The format of the relationship classification label you construct is as follows:
`[
    [0,1,0,0],
    [0,0,1,0]
        ...       ]` 

If a data set contains a total of four relationships, namely **_[A,B,C,D]_**, then the first line _[0,1,0,0]_ indicates that there is a relationship **_B_** between the corresponding entity pairs, the second line  _[0,0,1,0]_ indicates that there is a relationship **_C_** between the corresponding entity pairs.

There seems to be no doubt about the above, but the first and second rows may be the same entity pair sample. At this time, the label should be in the following form：
`[
    [0,1,1,0],
        ...       ]`

Finally, in the above two cases, the relation calssification loss is different, and the first is wrong.

**Comment by markus-eberts** [comment] 2021-04-28 08:32
Hi, 
thanks for your well described issue. I'm aware that this case is currently not handled correctly. It was not necessary for our paper, since the datasets we evaluated SpERT on did not contain multiple relations between the same entity pair. However, the model itself is build to handle such cases. Considering that our model (and code) is now also used on other datasets, I wanted to handle this case for some time, then postopened it due to other work and forgot about it. Thanks for reminding me, it is a good time to fix it now.

**Comment by markus-eberts** [comment] 2021-04-28 11:32
Should be fixed in commit 7b27b7d258d0b4bb44103b9d0f9e19f2ce08611f . Please leave a comment if the issue is still unsolved.

**Closed by markus-eberts** 2021-04-28 11:32 UTC
